package id.go.bpsfasih.data.mapper;

import androidx.constraintlayout.widget.ConstraintLayout;
import id.go.bpsfasih.FasihApp;
import id.go.bpsfasih.data.local.entities.LookupsList;
import id.go.bpsfasih.data.local.entities.SurveyEntity;
import id.go.bpsfasih.data.local.entities.TemplateLookupList;
import id.go.bpsfasih.data.remote.dto.LookupDto;
import id.go.bpsfasih.data.remote.dto.SurveyDto;
import id.go.bpsfasih.data.remote.dto.SurveyPeriodDto;
import id.go.bpsfasih.data.remote.dto.TemplateLookupDto;
import id.go.bpsfasih.data.remote.dto.UserRoleDto;
import id.go.bpsfasih.domain.models.Lookup;
import id.go.bpsfasih.domain.models.Survey;
import id.go.bpsfasih.domain.models.SurveyPeriod;
import id.go.bpsfasih.domain.models.TemplateLookup;
import id.go.bpsfasih.domain.models.UserRole;
import java.io.File;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import kotlin.jvm.internal.Intrinsics;

/* compiled from: SurveyMapper.kt */
@Metadata(d1 = {"\u00008\n\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010 \n\u0002\u0018\u0002\n\u0002\b\u0002\u001a\n\u0010\u0000\u001a\u00020\u0001*\u00020\u0002\u001a\n\u0010\u0000\u001a\u00020\u0003*\u00020\u0004\u001a\n\u0010\u0000\u001a\u00020\u0005*\u00020\u0006\u001a\n\u0010\u0000\u001a\u00020\u0007*\u00020\b\u001a\n\u0010\u0000\u001a\u00020\t*\u00020\n\u001a\u0016\u0010\u000b\u001a\b\u0012\u0004\u0012\u00020\r0\f*\b\u0012\u0004\u0012\u00020\u00030\f\u001a\n\u0010\u000e\u001a\u00020\r*\u00020\u0003¨\u0006\u000f"}, d2 = {"toDomain", "Lid/go/bpsfasih/domain/models/Lookup;", "Lid/go/bpsfasih/data/remote/dto/LookupDto;", "Lid/go/bpsfasih/domain/models/Survey;", "Lid/go/bpsfasih/data/remote/dto/SurveyDto;", "Lid/go/bpsfasih/domain/models/SurveyPeriod;", "Lid/go/bpsfasih/data/remote/dto/SurveyPeriodDto;", "Lid/go/bpsfasih/domain/models/TemplateLookup;", "Lid/go/bpsfasih/data/remote/dto/TemplateLookupDto;", "Lid/go/bpsfasih/domain/models/UserRole;", "Lid/go/bpsfasih/data/remote/dto/UserRoleDto;", "toEntities", "", "Lid/go/bpsfasih/data/local/entities/SurveyEntity;", "toEntity", "app_release"}, k = 2, mv = {1, 7, 1}, xi = ConstraintLayout.LayoutParams.Table.LAYOUT_CONSTRAINT_VERTICAL_CHAINSTYLE)
/* loaded from: classes2.dex */
public final class SurveyMapperKt {
    public static final Survey toDomain(SurveyDto surveyDto) {
        Intrinsics.checkNotNullParameter(surveyDto, "<this>");
        String id2 = surveyDto.getId();
        String name = surveyDto.getName();
        boolean panelType = surveyDto.getPanelType();
        boolean areaType = surveyDto.getAreaType();
        boolean updateListingType = surveyDto.getUpdateListingType();
        boolean canAddSample = surveyDto.getCanAddSample();
        boolean zIsMultiPencacah = surveyDto.isMultiPencacah();
        boolean geoLiveTracking = surveyDto.getGeoLiveTracking();
        int geoRadius = surveyDto.getGeoRadius();
        int geoAccuracy = surveyDto.getGeoAccuracy();
        String surveySampleTypeId = surveyDto.getSurveySampleTypeId();
        String surveySampleMethodId = surveyDto.getSurveySampleMethodId();
        String userId = surveyDto.getUserId();
        String createdDate = surveyDto.getCreatedDate();
        String surveyStepTypeId = surveyDto.getSurveyStepTypeId();
        String surveyParentId = surveyDto.getSurveyParentId();
        String cawiTokenAutoGenerated = surveyDto.getCawiTokenAutoGenerated();
        String regionGroupId = surveyDto.getRegionGroupId();
        List<TemplateLookupDto> templateLookup = surveyDto.getTemplateLookup();
        ArrayList arrayList = new ArrayList(CollectionsKt.collectionSizeOrDefault(templateLookup, 10));
        Iterator<T> it = templateLookup.iterator();
        while (it.hasNext()) {
            arrayList.add(toDomain((TemplateLookupDto) it.next()));
        }
        ArrayList arrayList2 = arrayList;
        List<SurveyPeriodDto> listPeriode = surveyDto.getListPeriode();
        ArrayList arrayList3 = new ArrayList(CollectionsKt.collectionSizeOrDefault(listPeriode, 10));
        Iterator<T> it2 = listPeriode.iterator();
        while (it2.hasNext()) {
            arrayList3.add(toDomain((SurveyPeriodDto) it2.next()));
        }
        return new Survey(id2, name, panelType, areaType, updateListingType, canAddSample, zIsMultiPencacah, geoLiveTracking, geoRadius, geoAccuracy, surveySampleTypeId, surveySampleMethodId, userId, createdDate, surveyStepTypeId, surveyParentId, cawiTokenAutoGenerated, regionGroupId, arrayList2, arrayList3, surveyDto.getSurveyGlossaries(), surveyDto.getSampleMethod(), surveyDto.getBackgroundRecord(), surveyDto.getSmallestRegionType(), surveyDto.getImageServiceType(), surveyDto.getImageServiceUrl(), surveyDto.getSurveyModes(), surveyDto.getAllowSync());
    }

    public static final TemplateLookup toDomain(TemplateLookupDto templateLookupDto) {
        Intrinsics.checkNotNullParameter(templateLookupDto, "<this>");
        String templateId = templateLookupDto.getTemplateId();
        String templateVersion = templateLookupDto.getTemplateVersion();
        int formEngineId = templateLookupDto.getFormEngineId();
        String formEngineBrandName = templateLookupDto.getFormEngineBrandName();
        List<LookupDto> lookups = templateLookupDto.getLookups();
        ArrayList arrayList = new ArrayList(CollectionsKt.collectionSizeOrDefault(lookups, 10));
        Iterator<T> it = lookups.iterator();
        while (it.hasNext()) {
            arrayList.add(toDomain((LookupDto) it.next()));
        }
        return new TemplateLookup(templateId, templateVersion, formEngineId, formEngineBrandName, arrayList);
    }

    public static final Lookup toDomain(LookupDto lookupDto) {
        Intrinsics.checkNotNullParameter(lookupDto, "<this>");
        return new Lookup(lookupDto.getId(), lookupDto.getVersion());
    }

    public static final SurveyPeriod toDomain(SurveyPeriodDto surveyPeriodDto) {
        Intrinsics.checkNotNullParameter(surveyPeriodDto, "<this>");
        String id2 = surveyPeriodDto.getId();
        String name = surveyPeriodDto.getName();
        String surveyId = surveyPeriodDto.getSurveyId();
        String parentId = surveyPeriodDto.getParentId();
        String userId = surveyPeriodDto.getUserId();
        String createdDate = surveyPeriodDto.getCreatedDate();
        String startDate = surveyPeriodDto.getStartDate();
        String endDate = surveyPeriodDto.getEndDate();
        boolean zIsActive = surveyPeriodDto.isActive();
        List<UserRoleDto> listUserRole = surveyPeriodDto.getListUserRole();
        ArrayList arrayList = new ArrayList(CollectionsKt.collectionSizeOrDefault(listUserRole, 10));
        Iterator<T> it = listUserRole.iterator();
        while (it.hasNext()) {
            arrayList.add(toDomain((UserRoleDto) it.next()));
        }
        return new SurveyPeriod(id2, name, surveyId, parentId, userId, createdDate, startDate, endDate, zIsActive, arrayList, surveyPeriodDto.getListSmallestRegionFullCode(), surveyPeriodDto.getSurveyPeriodeRoleUserId());
    }

    public static final UserRole toDomain(UserRoleDto userRoleDto) {
        Intrinsics.checkNotNullParameter(userRoleDto, "<this>");
        return new UserRole(userRoleDto.getId(), userRoleDto.getSequence(), userRoleDto.getDescription(), userRoleDto.getSurveyRoleGroupId(), userRoleDto.isApproving(), userRoleDto.isPencacah(), userRoleDto.getSmallestAreaOrder(), userRoleDto.getCanDrawSample(), userRoleDto.getCanChangeMode(), userRoleDto.getAdminTicket(), userRoleDto.getCanAccessTicket(), userRoleDto.getCanEdit(), userRoleDto.getCreatedAt(), userRoleDto.getUpdatedAt(), userRoleDto.getSurveyId());
    }

    public static final SurveyEntity toEntity(Survey survey) {
        Intrinsics.checkNotNullParameter(survey, "<this>");
        String userId = FasihApp.INSTANCE.getSession().getUserId();
        SurveyEntity surveyEntity = new SurveyEntity();
        surveyEntity.setIdPrimary(survey.getId() + File.separator + userId);
        surveyEntity.setId(survey.getId());
        surveyEntity.setActive(true);
        surveyEntity.setAreaType(survey.isAreaType());
        surveyEntity.setCanAddSample(survey.getCanAddSample());
        String cawiTokenAutoGenerated = survey.getCawiTokenAutoGenerated();
        surveyEntity.setCawiTokenAutoGenerated(cawiTokenAutoGenerated != null ? Boolean.parseBoolean(cawiTokenAutoGenerated) : false);
        surveyEntity.setCreatedDate(survey.getCreatedDate());
        surveyEntity.setGeoAccuracy(survey.getGeoAccuracy());
        surveyEntity.setGeoLiveTracking(survey.isGeoLiveTracking());
        surveyEntity.setGeoRadius(survey.getGeoRadius());
        String imageServiceType = survey.getImageServiceType();
        surveyEntity.setImageServiceType(imageServiceType != null ? Integer.parseInt(imageServiceType) : 0);
        surveyEntity.setImageServiceUrl(survey.getImageServiceUrl());
        surveyEntity.setName(survey.getName());
        surveyEntity.setPanelType(survey.isPanelType());
        surveyEntity.setSurveyParentId(survey.getSurveyParentId());
        surveyEntity.setSurveySampleMethodId(survey.getSurveySampleMethodId());
        surveyEntity.setSurveySampleTypeId(survey.getSurveySampleTypeId());
        surveyEntity.setSurveyStepTypeId(survey.getSurveyStepTypeId());
        TemplateLookup templateLookup = (TemplateLookup) CollectionsKt.firstOrNull((List) survey.getTemplateLookups());
        surveyEntity.setSurveyTemplateId(templateLookup != null ? templateLookup.getTemplateId() : null);
        surveyEntity.setSurveyTemplateListingId(null);
        surveyEntity.setUpdateListingType(survey.isUpdateListingType());
        surveyEntity.setUserId(userId);
        surveyEntity.setSelected(false);
        surveyEntity.setTarikSampleExclusive(null);
        surveyEntity.setSampleMethod(null);
        surveyEntity.setEngineIcs2(false);
        surveyEntity.setMultiPencacah(Boolean.valueOf(survey.isMultiPencacah()));
        surveyEntity.setRegionGroupId(survey.getRegionGroupId());
        surveyEntity.setBackgroundRecord(Boolean.valueOf(survey.isBackgroundRecord()));
        surveyEntity.setSmallestRegionType(Integer.valueOf(survey.getSmallestRegionType()));
        List<TemplateLookup> templateLookups = survey.getTemplateLookups();
        ArrayList arrayList = new ArrayList(CollectionsKt.collectionSizeOrDefault(templateLookups, 10));
        for (TemplateLookup templateLookup2 : templateLookups) {
            String templateId = templateLookup2.getTemplateId();
            List<Lookup> lookups = templateLookup2.getLookups();
            ArrayList arrayList2 = new ArrayList(CollectionsKt.collectionSizeOrDefault(lookups, 10));
            for (Lookup lookup : lookups) {
                arrayList2.add(new LookupsList(lookup.getId(), lookup.getVersion()));
            }
            arrayList.add(new TemplateLookupList(templateId, arrayList2));
        }
        surveyEntity.setTemplateLookup(arrayList);
        surveyEntity.setSurveyModes(survey.getSurveyModes());
        return surveyEntity;
    }

    public static final List<SurveyEntity> toEntities(List<Survey> list) {
        Intrinsics.checkNotNullParameter(list, "<this>");
        List<Survey> list2 = list;
        ArrayList arrayList = new ArrayList(CollectionsKt.collectionSizeOrDefault(list2, 10));
        Iterator<T> it = list2.iterator();
        while (it.hasNext()) {
            arrayList.add(toEntity((Survey) it.next()));
        }
        return arrayList;
    }
}
